### PR TITLE
fix portal maps (due to saving)

### PR DESCRIPTION
**Pull request by ThePixelMoon**
yeah..

### CODE REVIEW

**Comment by andrewmcwatters** [comment]
Could you explain the issue?

**Comment by ThePixelMoon** [comment]
> Could you explain the issue?

when loading portal 1 maps, a crash could happen due to saving and stuff

mostly because of autosaving

**Comment by andrewmcwatters** [comment]
OK, let's merge this, but can you link to any external sources that reference this issue? Valve Developer Community, etc? I'll set up a test case for this.

**Comment by ThePixelMoon** [comment]
> OK, let's merge this, but can you link to any external sources that reference this issue? Valve Developer Community, etc? I'll set up a test case for this.

knowledge of #ifndef and debugging

**Comment by ThePixelMoon** [comment]
otherwise, nowhere

**Comment by andrewmcwatters** [comment]
This is an insufficient explanation of the issue.

**Pull request closed without merging**
