### PR TITLE
increase some "common limits"

### PR DESCRIPTION
**Pull request by ThePixelMoon**
image

suggested by a contributor of my mod, this may be used for stuff like vbsp or vrad, i don't know honestly

### CODE REVIEW

**Comment by ThePixelMoon** [comment]
if i remember correctly, its only for the utils/tools

**Comment by andrewmcwatters** [comment]
@Jacobdeanr Can you look this over? It would be nice to understand these historical limits.

**Comment by Jacobdeanr** [comment]
If we're raising limits of entities we should also update MAX_GROUP_ENTITIES in src/game/client
/clientleafsystem.h

**Comment by andrewmcwatters** [comment]
@Jacobdeanr If these limits were historically for performance reasons, can or should we "remove" them by just assigning their maximum data type value?

**Comment by ThePixelMoon** [comment]
> If we're raising limits of entities we should also update MAX_GROUP_ENTITIES in src/game/client /clientleafsystem.h

done.

**Comment by Jacobdeanr** [comment]
It'll take time to review. Brush limit is there for bevel edges (axis aligned faces) that must generate. For example if a map has angled geo, it'll be sliced along the grid axis for qphysics. Brush faces are also occupied by a boundind face for angled geo. Raising to 16k could cause the face limit to be reached in the bsp file if somebody made their map with a lot of angeled geo.
It should be safe to implement the entity limit changes as vbsp merely reports how many entities are in the level. But I think it would be best to hold off merging the brush limit changes until further research is done.

**Comment by Jacobdeanr** [comment]
This pull Request seems to be primarily focused on changing vbsp but im seeing a change to ammo limits i
For game code. Could we focus the pull request for a single feature change? @ThePixelMoon

**Comment by ThePixelMoon** [comment]
> This pull Request seems to be primarily focused on changing vbsp but im seeing a change to ammo limits in game code. Could we focus the pull request for a single feature change? @ThePixelMoon

sorry got distracted @Jacobdeanr

**Comment by andrewmcwatters** [comment]
Also, in practice, even with a lot of scripted weapons, I've found that altering the ammo and weapon slots doesn't actually amount to much. I would just drop that commit in your `git rebase`.

**Pull request closed without merging**
