### PR TITLE
HTML Main Menu

### PR DESCRIPTION
**Pull request by GuestSneezeOSDev**
the code is from my friend YourLocalMoon's mod named [OpenMod](https://github.com/ThePixelMoon/OpenMod)

### CODE REVIEW

**Comment by ThePixelMoon** [comment]
BRO THE SOURCE 2013 PORT ISNT EVEN DONE YET

**Comment by ThePixelMoon** [comment]
image
WHAT

**Comment by GuestSneezeOSDev** [comment]
> image WHAT

deleted sp dir

**Comment by ThePixelMoon** [comment]
WHY

**Comment by GuestSneezeOSDev** [comment]
> WHY

hl2sb is based on the mp branch of the srceng

**Comment by andrewmcwatters** [comment]
@GuestSneezeOSDev Nice work! Let's try to keep PRs related to just what they're changing though. I see you removed the `sp` folder, but it's not what this patch is about. Can you remove that part of your pull request, please?

**Comment by GuestSneezeOSDev** [comment]
> @GuestSneezeOSDev Nice work! Let's try to keep PRs related to just what they're changing though. I see you removed the `sp` folder, but it's not what this patch is about. Can you remove that part of your pull request, please?

Alright

**Pull request closed without merging**
